name: DEPLOY_TO_EC2

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Install WebAssembly target
        run: rustup target add wasm32-unknown-unknown

      - name: Install trunk
        run: cargo install trunk

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install mccli to enable SSH with OIDC authentication
        run: pip install mccli

      - name: Build the project
        run: trunk build --release

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::471112525273:role/github-oidc
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          rsync -avzr -vvv --delete --exclude '.git/' --exclude '.github/' -e "mccli ssh -o StrictHostKeyChecking=no --oidc" ./dist/ $USER@$HOST:~/dist
          rm -f private_key.pem
